### ISSUE TITLE
[Feature Request] Allow mods stick and prevent auto hide

### ISSUE THREAD

**Issue by BevoLJ** [malahx/QuickHide#1]
o/

Amazing mods!  I was wondering if you might be able to allow mods to stick when clicked so they prevent the auto hide feature.  I love the feature but it makes it very hard to use mods like Kerbal Engineer.

**Comment by malahx** [comment]
Nice idea, I will work on it ;)

**Comment by BevoLJ** [comment]
Rock on!  \o/  

Cheers m8.

**Comment by curiousepic** [comment]
Any update on this feature? Stock toolbar is getting overloaded post-1.0!

**Comment by malahx** [comment]
I work on it ... you need to wait a little more ;)
